### PR TITLE
Made it good

### PR DESCRIPTION
**Pull request by Reaxt**
improved example with good

### CODE REVIEW

**Comment by islacantwin** [comment]
same

**Comment by aurieh** [comment]
me too thanks

**Comment by jakeoid** [comment]
@aurieh Im not the main contributor you heck

**Comment by TheVexatious** [comment]
lolwut i don't understand the unnecessary `if(true === true) {`'s and all those memes :eyes: , plus, the indentation is pretty screwed :eyes: :eyes: 

also dean.png doesn't exist...?

**Comment by deansheather** [comment]
\>the point

**Comment by islacantwin** [comment]
^

**Comment by sr229** [comment]
No Fuck you.

**Comment by islacantwin** [comment]
No sense of humor smh

**Comment by sr229** [comment]
@OkashiOdayakana we expect you to act professionally, PRs are not to be taken lightly.

**Pull request closed without merging**
