### PR TITLE
Fixed `owo.py` to `owo.js`

### PR DESCRIPTION
**Pull request by TTtie**
Just a little fix in a typo.

### CODE REVIEW

**Comment by aurieh** [comment]
👀

**Comment by TheVexatious** [comment]
readme always has a problem with it, 
(╯°□°）╯︵ ┻━┻

**Comment by TTtie** [comment]
~~we know.~~

**Comment by aurieh** [comment]
🌱 #PRFarm

**Comment by TTtie** [comment]
ik *farms PRs*

**Comment by jakeoid** [comment]
Damnit, thanks.

**Pull request merged**
