### PR TITLE
yay cli

### PR DESCRIPTION
**Pull request by devsnek**

### CODE REVIEW

**Review by aurieh — CHANGES_REQUESTED** [review]
ES7 NotLikeThis, please babel it.

**Comment by devsnek** [comment]
async/await is native without harmony flags. git gud.

**Comment by aurieh** [comment]
Node 6 is still LTS.

**Review by sr229 — DISMISSED** [review]
I won't accept this


**THIS SHOULD BE IN ES6**

**Comment by sr229** [comment]
Think about the children Gus. **Make this Promise or it would not be merged**

**Comment by devsnek** [comment]
async/await is es6 you weirdo kiddies

**Comment by aurieh** [comment]
@GusCaplan I never said it wasn't (smh @sr229), but the CLI should be compliant with LTS.

**Comment by sr229** [comment]
My Point stands.

Make this compatible with Nodev6.

**Review by sr229 — CHANGES_REQUESTED** [review]
I mean

IT IS valid ES6 but not LTS compatible (v6.10.0)

**Review by sr229 — APPROVED** [review]
NUT

**Review by aurieh — APPROVED** [review]

**Comment by sr229** [comment]
Needs more Australian memes

**Pull request merged**
